/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ForgotPinRouteImport } from './routes/forgot-pin'
import { Route as HowAjoWorksRouteImport } from './routes/how-ajo-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPinRouteImport } from './routes/reset-pin'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SplitBillsRouteImport } from './routes/split-bills'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAjoRouteImport } from './routes/_app/admin/ajo'
import { Route as AppAdminHealthRouteImport } from './routes/_app/admin/health'
import { Route as AppAdminTransactionsRouteImport } from './routes/_app/admin/transactions'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAjoIndexRouteImport } from './routes/_app/ajo/index'
import { Route as AppAjoGroupIdRouteImport } from './routes/_app/ajo/$groupId'
import { Route as AppAjoNewRouteImport } from './routes/_app/ajo/new'
import { Route as AppBillsIndexRouteImport } from './routes/_app/bills/index'
import { Route as AppBillsBillIdRouteImport } from './routes/_app/bills/$billId'
import { Route as AppBillsNewRouteImport } from './routes/_app/bills/new'
import { Route as AppAjoJoinGroupIdRouteImport } from './routes/_app/ajo/join.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPinRoute = ForgotPinRouteImport.update({
  id: '/forgot-pin',
  path: '/forgot-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const HowAjoWorksRoute = HowAjoWorksRouteImport.update({
  id: '/how-ajo-works',
  path: '/how-ajo-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPinRoute = ResetPinRouteImport.update({
  id: '/reset-pin',
  path: '/reset-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitBillsRoute = SplitBillsRouteImport.update({
  id: '/split-bills',
  path: '/split-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAjoRoute = AppAdminAjoRouteImport.update({
  id: '/ajo',
  path: '/ajo',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTransactionsRoute = AppAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAjoIndexRoute = AppAjoIndexRouteImport.update({
  id: '/ajo/',
  path: '/ajo/',
  getParentRoute: () => AppRoute,
} as any)
const AppAjoGroupIdRoute = AppAjoGroupIdRouteImport.update({
  id: '/ajo/$groupId',
  path: '/ajo/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppAjoNewRoute = AppAjoNewRouteImport.update({
  id: '/ajo/new',
  path: '/ajo/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIndexRoute = AppBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsBillIdRoute = AppBillsBillIdRouteImport.update({
  id: '/bills/$billId',
  path: '/bills/$billId',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsNewRoute = AppBillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAjoJoinGroupIdRoute = AppAjoJoinGroupIdRouteImport.update({
  id: '/ajo/join/$groupId',
  path: '/ajo/join/$groupId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/how-ajo-works': typeof HowAjoWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-pin': typeof ResetPinRoute
  '/security': typeof SecurityRoute
  '/split-bills': typeof SplitBillsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/ajo': typeof AppAdminAjoRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/ajo/$groupId': typeof AppAjoGroupIdRoute
  '/ajo/new': typeof AppAjoNewRoute
  '/bills/$billId': typeof AppBillsBillIdRoute
  '/bills/new': typeof AppBillsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/ajo/': typeof AppAjoIndexRoute
  '/bills/': typeof AppBillsIndexRoute
  '/ajo/join/$groupId': typeof AppAjoJoinGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/how-ajo-works': typeof HowAjoWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-pin': typeof ResetPinRoute
  '/security': typeof SecurityRoute
  '/split-bills': typeof SplitBillsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/ajo': typeof AppAdminAjoRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/ajo/$groupId': typeof AppAjoGroupIdRoute
  '/ajo/new': typeof AppAjoNewRoute
  '/bills/$billId': typeof AppBillsBillIdRoute
  '/bills/new': typeof AppBillsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/ajo': typeof AppAjoIndexRoute
  '/bills': typeof AppBillsIndexRoute
  '/ajo/join/$groupId': typeof AppAjoJoinGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/how-ajo-works': typeof HowAjoWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-pin': typeof ResetPinRoute
  '/security': typeof SecurityRoute
  '/split-bills': typeof SplitBillsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/admin/ajo': typeof AppAdminAjoRoute
  '/_app/admin/health': typeof AppAdminHealthRoute
  '/_app/admin/transactions': typeof AppAdminTransactionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/ajo/$groupId': typeof AppAjoGroupIdRoute
  '/_app/ajo/new': typeof AppAjoNewRoute
  '/_app/bills/$billId': typeof AppBillsBillIdRoute
  '/_app/bills/new': typeof AppBillsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/ajo/': typeof AppAjoIndexRoute
  '/_app/bills/': typeof AppBillsIndexRoute
  '/_app/ajo/join/$groupId': typeof AppAjoJoinGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/forgot-pin'
    | '/how-ajo-works'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-pin'
    | '/security'
    | '/split-bills'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/admin/ajo'
    | '/admin/health'
    | '/admin/transactions'
    | '/admin/users'
    | '/ajo/$groupId'
    | '/ajo/new'
    | '/bills/$billId'
    | '/bills/new'
    | '/admin/'
    | '/ajo/'
    | '/bills/'
    | '/ajo/join/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/forgot-pin'
    | '/how-ajo-works'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-pin'
    | '/security'
    | '/split-bills'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/admin/ajo'
    | '/admin/health'
    | '/admin/transactions'
    | '/admin/users'
    | '/ajo/$groupId'
    | '/ajo/new'
    | '/bills/$billId'
    | '/bills/new'
    | '/admin'
    | '/ajo'
    | '/bills'
    | '/ajo/join/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/design-system'
    | '/forgot-pin'
    | '/how-ajo-works'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-pin'
    | '/security'
    | '/split-bills'
    | '/terms'
    | '/verify-email'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/wallet'
    | '/_app/admin/ajo'
    | '/_app/admin/health'
    | '/_app/admin/transactions'
    | '/_app/admin/users'
    | '/_app/ajo/$groupId'
    | '/_app/ajo/new'
    | '/_app/bills/$billId'
    | '/_app/bills/new'
    | '/_app/admin/'
    | '/_app/ajo/'
    | '/_app/bills/'
    | '/_app/ajo/join/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPinRoute: typeof ForgotPinRoute
  HowAjoWorksRoute: typeof HowAjoWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPinRoute: typeof ResetPinRoute
  SecurityRoute: typeof SecurityRoute
  SplitBillsRoute: typeof SplitBillsRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-pin': {
      id: '/forgot-pin'
      path: '/forgot-pin'
      fullPath: '/forgot-pin'
      preLoaderRoute: typeof ForgotPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-ajo-works': {
      id: '/how-ajo-works'
      path: '/how-ajo-works'
      fullPath: '/how-ajo-works'
      preLoaderRoute: typeof HowAjoWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-pin': {
      id: '/reset-pin'
      path: '/reset-pin'
      fullPath: '/reset-pin'
      preLoaderRoute: typeof ResetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-bills': {
      id: '/split-bills'
      path: '/split-bills'
      fullPath: '/split-bills'
      preLoaderRoute: typeof SplitBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ajo': {
      id: '/_app/admin/ajo'
      path: '/ajo'
      fullPath: '/admin/ajo'
      preLoaderRoute: typeof AppAdminAjoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/health': {
      id: '/_app/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/transactions': {
      id: '/_app/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AppAdminTransactionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/ajo/': {
      id: '/_app/ajo/'
      path: '/ajo'
      fullPath: '/ajo/'
      preLoaderRoute: typeof AppAjoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajo/$groupId': {
      id: '/_app/ajo/$groupId'
      path: '/ajo/$groupId'
      fullPath: '/ajo/$groupId'
      preLoaderRoute: typeof AppAjoGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajo/new': {
      id: '/_app/ajo/new'
      path: '/ajo/new'
      fullPath: '/ajo/new'
      preLoaderRoute: typeof AppAjoNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/': {
      id: '/_app/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AppBillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/$billId': {
      id: '/_app/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AppBillsBillIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/new': {
      id: '/_app/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AppBillsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajo/join/$groupId': {
      id: '/_app/ajo/join/$groupId'
      path: '/ajo/join/$groupId'
      fullPath: '/ajo/join/$groupId'
      preLoaderRoute: typeof AppAjoJoinGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAjoRoute: typeof AppAdminAjoRoute
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminTransactionsRoute: typeof AppAdminTransactionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAjoRoute: AppAdminAjoRoute,
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminTransactionsRoute: AppAdminTransactionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppAjoGroupIdRoute: typeof AppAjoGroupIdRoute
  AppAjoNewRoute: typeof AppAjoNewRoute
  AppBillsBillIdRoute: typeof AppBillsBillIdRoute
  AppBillsNewRoute: typeof AppBillsNewRoute
  AppAjoIndexRoute: typeof AppAjoIndexRoute
  AppBillsIndexRoute: typeof AppBillsIndexRoute
  AppAjoJoinGroupIdRoute: typeof AppAjoJoinGroupIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletRoute: AppWalletRoute,
  AppAjoGroupIdRoute: AppAjoGroupIdRoute,
  AppAjoNewRoute: AppAjoNewRoute,
  AppBillsBillIdRoute: AppBillsBillIdRoute,
  AppBillsNewRoute: AppBillsNewRoute,
  AppAjoIndexRoute: AppAjoIndexRoute,
  AppBillsIndexRoute: AppBillsIndexRoute,
  AppAjoJoinGroupIdRoute: AppAjoJoinGroupIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPinRoute: ForgotPinRoute,
  HowAjoWorksRoute: HowAjoWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPinRoute: ResetPinRoute,
  SecurityRoute: SecurityRoute,
  SplitBillsRoute: SplitBillsRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
