name: Web

on:
  push:
    branches: ["master"]
    paths: ["web/**", ".github/workflows/web.yml"]
  pull_request:
    branches: ["master"]
    paths: ["web/**", ".github/workflows/web.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build
        env:
          NEXT_PUBLIC_COWRI_API_URL: "https://api.cowri.app/v1"
